### ISSUE TITLE
calling `axiosCookieJarSupport(axios)` more than once seems to break axios

### ISSUE THREAD

**Issue by seanmarthur** [3846masa/axios-cookiejar-support#141]
I built a small utility library that will authenticate to a service and return the cookie jar, for use in other requests.

In my apps which use this library, if I load axios and call `axiosCookieJarSupport(axios);`, all requests will fail with:

```
name=RangeError, message=Maximum call stack size exceeded, stack=RangeError: Maximum call stack size exceeded
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:247:15)
    at assignValue (C:\EDSS\node_modules\axios\lib\utils.js:251:21)
    at forEach (C:\EDSS\node_modules\axios\lib\utils.js:224:12)
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:258:5)
    at assignValue (C:\EDSS\node_modules\axios\lib\utils.js:251:21)
    at forEach (C:\EDSS\node_modules\axios\lib\utils.js:224:12)
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:258:5)
    at assignValue (C:\EDSS\node_modules\axios\lib\utils.js:251:21)
    at forEach (C:\EDSS\node_modules\axios\lib\utils.js:224:12)
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:258:5)
    at assignValue (C:\EDSS\node_modules\axios\lib\utils.js:251:21)
    at forEach (C:\EDSS\node_modules\axios\lib\utils.js:224:12)
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:258:5)
    at assignValue (C:\EDSS\node_modules\axios\lib\utils.js:251:21)
    at forEach (C:\EDSS\node_modules\axios\lib\utils.js:224:12)
    at merge (C:\EDSS\node_modules\axios\lib\utils.js:258:5)
```

The fix for this is to allow my library to call `axiosCookieJarSupport(axios);` and then ensure no downstream users ever call it again. This isn't a huge deal for me, but I think this library could handle this case.

Should calling `axiosCookieJarSupport(axios);` multiple times result in no operation performed, or maybe a warning log, or exception thrown?

**Comment by 3846masa** [comment]
@seanmarthur Thanks for reporting!
I fixed and I'll release as v0.3.5.
