### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by moltar** [3846masa/axios-cookiejar-support#227]
```
git clone ...
npm i
npm t
```

  ```
❯ npm t

> axios-cookiejar-support@0.5.0 test .../axios-cookiejar-support
> mocha test.spec.js --require intelli-espower-loader

Error: Cannot find module './'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (.../axios-cookiejar-support/test.spec.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.extensions..js (.../axios-cookiejar-support/node_modules/espower-loader/index.js:47:13)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at .../axios-cookiejar-support/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (.../axios-cookiejar-support/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (.../axios-cookiejar-support/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (.../axios-cookiejar-support/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (.../axios-cookiejar-support/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (.../axios-cookiejar-support/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (.../axios-cookiejar-support/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (.../axios-cookiejar-support/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (.../axios-cookiejar-support/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (.../axios-cookiejar-support/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (.../axios-cookiejar-support/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by 3846masa** [comment]
Please build first.
`npm run build`
