### ISSUE TITLE
TypeError: Cannot read property 'backupOptions' of undefined

### ISSUE THREAD

**Issue by lmj0011** [3846masa/axios-cookiejar-support#87]
```
TypeError: Cannot read property 'backupOptions' of undefined
    at backupOriginalConfigs (/home/landan/www/adonuxt-rp/node_modules/@3846masa/axios-cookiejar-support/lib/request-interceptor-wrapper.js:7:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

```js
const axios = require('axios')
const axiosCookieJarSupport = require('@3846masa/axios-cookiejar-support')
const tough = require('tough-cookie')
axiosCookieJarSupport(axios)

const cookieJar = new tough.CookieJar()

//[...]
getInstanceGitInfo () {
    let options = {}
    options.headers = {}

    options.headers['Accept'] = 'application/json'
    options.headers['Content-Type'] = 'application/json'
    options.headers['X-Requested-With'] = 'XMLHttpRequest'

    let api = axios.create(options)

    // https://github.com/mzabriskie/axios#interceptors
    api.interceptors.response.use(function (response) {
      return response.data || response
    }, function (error) {
      return Promise.reject(error)
    })

    return api({
      method: 'post',
      url: 'http://www.example.com/login',
      jar: cookieJar,
      withCredentials: true,
      data: {
        username: 'user',
        password: 'xxxxxxx'
      }
    })
    .then(() => {
      return api.get('http://www.example.com/admin/system/info', { jar: cookieJar, withCredentials: true })
    })
    .catch(err => {
      console.log(err)
    })
  }
```

I'm unsure why I'm getting this error

**Comment by 3846masa** [comment]
`axios.interceptors.response.use` argument is required Function that will return `response`, not other data.
So, your interceptor is invalid usage.

```
api.interceptors.response.use(function (response) {
  // return response.data || response
  /* You must returns Response Object. */
  return response
}, function (error) {
  return Promise.reject(error)
})
```

See https://github.com/mzabriskie/axios/blob/v0.16.1/index.d.ts#L92-L110 .

**Comment by lmj0011** [comment]
where is the `backupOptions` coming from?

**Comment by 3846masa** [comment]
[Here](https://github.com/3846masa/axios-cookiejar-support/blob/v0.0.4/lib/request-interceptor-wrapper.js#L7) (Read error message you received, plz)

`axios-cookiejar-support` modify response-object via interceptor, but you pass other data to `axios-cookiejar-support`'s interceptor, so Error occurred.

**Comment by 3846masa** [comment]
Closed.
If you have issues yet, please resend issue.

**Comment by machineghost** [comment]
A more helpful error message, like say "Hey dummy you forgot to include jar: cookieJar in your axios config" would make this much less painful.

**Comment by 3846masa** [comment]
I see.
However, this issue's case caused from wrong usage in original axios.
So, this library should not warn Error in a situation like this issue's case.

If you want that this library will warn Error in other situation, **please create new issue** with more details.
**This issue was closed.**
