### ISSUE TITLE
TypeError: axiosCookieJarSupport is not a function

### ISSUE THREAD

**Issue by Xractz** [3846masa/axios-cookiejar-support#928]
## BUG

why i can't use axiosCookieJarSupport(axios);

## My Code
```js
const axios = require("axios").default;
const tough = require("tough-cookie");
const axiosCookieJarSupport = require("axios-cookiejar-support").default;

const cookieJar = new tough.CookieJar();
axiosCookieJarSupport(axios);
axios.defaults.jar = cookieJar;

const instance = axios.create({
  withCredentials: true,
  rejectUnauthorized: false,
});

instance
  .get(url)
  .then((response) => {
    const viewState = response.data.match(/id="__VIEWSTATE" value="(.*?)"/)[1];
    const viewStateGenerator = response.data.match(/id="__VIEWSTATEGENERATOR" value="(.*?)"/)[1];
    const eventValidation = response.data.match(/id="__EVENTVALIDATION" value="(.*?)"/)[1];

    const data = {
      __EVENTTARGET: "ctl00$MainContent$TextBox1",
      __EVENTARGUMENT: "",
      __LASTFOCUS: "",
      __VIEWSTATE: viewState,
      __VIEWSTATEGENERATOR: viewStateGenerator,
      __EVENTVALIDATION: eventValidation,
      ctl00$MainContent$TextBox1: "",
      ctl00$MainContent$TxtEmail: "",
      ctl00$MainContent$TxtTlp: "",
      ctl00$MainContent$txtTitle: "",
      ctl00$MainContent$FileUpload1: "",
    };

    instance({
      method: "post",
      url: url,
      data: data,
    })
      .then((response) => {
        console.log(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  })
  .catch((error) => {
    console.error(error);
  });

```

## ERROR

```JS
axiosCookieJarSupport(axios);
  ^

TypeError: axiosCookieJarSupport is not a function
    at main (D:\botwa\file.js:11:3)
    at Object.<anonymous> (D:\botwa\file.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.0
```

**Comment by noxyz20** [comment]
Hello @Xractz  if you follow the project documentation, you should use
```
import axios from 'axios';
import { wrapper } from 'axios-cookiejar-support';
import { CookieJar } from 'tough-cookie';

const jar = new CookieJar();
const client = wrapper(axios.create({ jar }));
```
Your code should look more like this 
```
const axios = require('axios');
const { wrapper } = require('axios-cookiejar-support');
const { CookieJar } = require('tough-cookie');

const cookieJar = new CookieJar();
wrapper(axios);
axios.defaults.jar = cookieJar;

const instance = axios.create({
    withCredentials: true,
    rejectUnauthorized: false,
  });

instance.get(....)
```

**Comment by Xractz** [comment]
Thanks
