### ISSUE TITLE
Axios config.baseURL is lost in redirect

### ISSUE THREAD

**Issue by blai** [3846masa/axios-cookiejar-support#93]
If I have an Axios instance that has a `baseURL`, it is lost with `axios-cookiejar-support` and thus stops working. Imagine the following pseudo code

```js
const http = require('http')
const express = require('express')
const axios = require('axios')
const tough = require('tough-cookie')

require('@3846masa/axios-cookiejar-support')(axios)

const app = express()

app.get('/foo', (req, res) => res.redirect('/bar'))
app.get('/bar', (req, res) => res.send('bar'))

describe('/foo', () => {
  let server
  let request

  beforeEach((done) => {
    let s = http.createServer(app)
    server = s.listen(0, () => { // random port
      let port     = s.address().port
      let baseURL  = `http://127.0.0.1:${port}`
      let jar      = new tough.CookieJar()
      let config   = {
        baseURL,
        jar,
        withCredentials: true,
        validateStatus(status) {
          return true
        }
      }

      request = axios.create(config)
      done()
    })
  })

  afterEach(() => server.close())

  it('redirect', async () => {
    let res = await request.get('/foo')

    assert(res.data === 'bar')
  })
})
```

The test will fail with the following output
```
    0 passing (53ms)
    1 failing

    1) foo redirect:
       Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.exports._errnoException (util.js:1016:11)
        at exports._exceptionWithHostPort (util.js:1039:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
```

Debug through can find that there were two request going out
```
// origin request
http://127.0.0.1:52815/foo

// redirect request
http://127.0.0.1/bar
```

Trace the code and found that we are explicitly setting `config.baseURL = undefined` here: https://github.com/3846masa/axios-cookiejar-support/blob/master/lib/response-interceptor-wrapper.js#L37

What are the reasoning behind this resetting of `config.baseURL`? Can we remove that line?

**Comment by 3846masa** [comment]
Thanks for issue.
I'll fix it.

**Comment by 3846masa** [comment]
https://github.com/3846masa/axios-cookiejar-support/pull/94
